-- Criar tabela para chuteiras de Campo
CREATE TABLE public.chuteiras_campo (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome text NOT NULL,
  tamanho text,
  url_imagem text
);

-- Criar tabela para chuteiras de Futsal
CREATE TABLE public.chuteiras_futsal (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome text NOT NULL,
  tamanho text,
  url_imagem text
);

-- Criar tabela para chuteiras de Society
CREATE TABLE public.chuteiras_society (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome text NOT NULL,
  tamanho text,
  url_imagem text
);

-- Copiar dados existentes da tabela chuteiras para chuteiras_campo
INSERT INTO public.chuteiras_campo (nome, tamanho, url_imagem)
SELECT nome, tamanho, url_imagem FROM public.chuteiras;

-- Habilitar RLS nas novas tabelas
ALTER TABLE public.chuteiras_campo ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chuteiras_futsal ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chuteiras_society ENABLE ROW LEVEL SECURITY;

-- Criar políticas de acesso público para leitura
CREATE POLICY "Permitir leitura pública de chuteiras_campo"
ON public.chuteiras_campo FOR SELECT
USING (true);

CREATE POLICY "Permitir leitura pública de chuteiras_futsal"
ON public.chuteiras_futsal FOR SELECT
USING (true);

CREATE POLICY "Permitir leitura pública de chuteiras_society"
ON public.chuteiras_society FOR SELECT
USING (true);